# Configuration file for repository processing and image generation

# Author list for markdown files
author_list:
  - "John Doe"
  - "Jane Smith"
  - "Alice Cooper"
  - "Bob Johnson"

# Output folder for generated markdown files
output_folder: "appleblog/src/pages/posts"

# Folder to store the generated images
image_folder: "appleblog/public/assets"

# Base URL for serving images, update this to match your server setup
base_url: "http://localhost:3000/"

# GitHub username to fetch repositories from
username: "wanghaisheng"

image_api_url: "https://fluxapi.borninsea.com/v1/chat/completions"

# OpenAI model for chat
openai:
  model: "gpt-4o-mini"  # Set the model name you want to use

# Specify the number of days within which repositories are considered "recently updated"
days_threshold: 1
